# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Do not keep production secrets in the repository,
# instead read values from the environment.
common: &common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  secret_key_base: c669a5954432f82b9ba51b16a0222d8f0e92672bcd860e229b135e68456de69b43c3d3b8ccb5d1888317af7076403249f5a511fba809e25073bdaa1302fa8aa6

test:
  secret_key_base: feebfd85c5d2ba782f0083dd39fd1cc8c58dde2404d0ed102069ce670ad5e5e0b7c805136f9cdee2e52b717976189ae5f40bfecce7e1525422b8a61ddda2fc96

staging:
  <<: *common

production:
  <<: *common
